version: 1.0.{build}

image: Visual Studio 2013

configuration: Release

platform:
- x86
- x64

before_build:
- curl -LsSO http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar
- del freetype-2.7.1.tar freetype-2.7.1.tar.bz2

build:
  verbosity: minimal

after_build:
- cd freetype-2.7.1

test: off