version: 1.0.{build}

image: Visual Studio 2013

configuration: Release

environment:
  pound: "#"
  matrix:
  - platform: x86
    outdir: Win32
  - platform: x64
    outdir: x64

shallow_clone: true

before_build:
- curl -LsSO http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar
- del freetype-2.7.1.tar freetype-2.7.1.tar.bz2

build_script:
- cd freetype-2.7.1
- ..\findreplace.bat ">StaticLibrary<" ">DynamicLibrary<" builds\windows\vc2010\freetype.vcxproj
- ..\findreplace.bat "v100" "v120" builds\windows\vc2010\freetype.vcxproj
- ..\findreplace.bat "/* %pound%define FT_EXPORT(x)      extern x */" "%pound%define FT_EXPORT(x) __declspec(dllexport) x" include\freetype\config\ftoption.h
- ..\findreplace.bat "/* %pound%define FT_EXPORT_DEF(x)  x */" "%pound%define FT_EXPORT_DEF(x) __declspec(dllexport) x" include\freetype\config\ftoption.h
- msbuild /t:Rebuild /p:Configuration=Release builds\windows\vc2010\freetype.vcxproj
- cd ..

after_build:
- mkdir freetype-2.7.1-shared-%PLATFORM%
- cd freetype-2.7.1-shared-%PLATFORM%
- mkdir include
- mkdir lib
- mkdir bin
- xcopy /e ..\freetype-2.7.1\include include
- copy ..\freetype-2.7.1\objs\vc2010\%outdir%\freetype271.lib lib
- copy ..\freetype-2.7.1\objs\vc2010\%outdir%\freetype271.dll bin
- copy ..\freetype-2.7.1\docs\LICENSE.TXT .
- copy ..\freetype-2.7.1\docs\FTL.TXT .
- copy ..\freetype-2.7.1\docs\GPLv2.TXT .
- cd ..
- 7z a -tzip freetype-2.7.1-shared-%PLATFORM%.zip freetype-2.7.1-shared-%PLATFORM%
- dir

artifacts:
  - path: freetype-2.7.1-shared-$(PLATFORM).zip
    name: freetype-2.7.1-shared-$(PLATFORM)

test: off

deploy:
  release: freetype-2.7.1-shared-$(PLATFORM)
  description: "FreeType 2.7.1 ($(PLATFORM))"
  provider: GitHub
  auth_token:
    secure: PF/wHCfSMFPCYyFh3GgjEJDHoPyPOnrmmbVMMwe8cNQBw2NL0vaYxjL1QcjMfpvL
  artifact: freetype-2.7.1-shared-$(PLATFORM)
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true # deploy on tag push only
