version: 1.0.{build}

image: Visual Studio 2013

configuration: Release

#platform:
#- x86
#- x64
environment:
  pound: ^#
  pound2: "#"
  matrix:
  - platform: x86
    outdir: Win32
  - platform: x64
    outdir: x64

shallow_clone: true

before_build:
- curl -LsSO http://download.savannah.gnu.org/releases/freetype/freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar.bz2
- 7z x freetype-2.7.1.tar
- del freetype-2.7.1.tar freetype-2.7.1.tar.bz2

build_script:
- cd freetype-2.7.1
- ..\findreplace.bat ">StaticLibrary<" ">DynamicLibrary<" builds\windows\vc2010\freetype.vcxproj
- ..\findreplace.bat "v100" "v120" builds\windows\vc2010\freetype.vcxproj
- ..\findreplace.bat "/* %pound%define FT_EXPORT(x)      extern x */" "%pound%define FT_EXPORT(x) __declspec(dllexport) x" include\freetype\config\ftoption.h
- ..\findreplace.bat "/* %pound%define FT_EXPORT_DEF(x)  x */" "%pound%define FT_EXPORT_DEF(x) __declspec(dllexport) x" include\freetype\config\ftoption.h
- msbuild /t:Rebuild /p:Configuration=Release builds\windows\vc2010\freetype.vcxproj
- echo "/* %pound%define FT_EXPORT(x)      extern x */" "%pound%define FT_EXPORT(x) __declspec(dllexport) x"
- echo %pound%
- echo %pound2%

after_build:
- cd objs\vc2010\%outdir%
- dir

test: off
